[project]
name = "sts2-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "Jim Wild",email = "james.wild@airelogic.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = []


[tool.poetry]
package-mode = false


[tool.poetry.dependencies]
python = ">=3.12,<4.0"
card-pick-model = { path = "card_pick_model", develop = true }
sts2-downloader = { path = "downloader", develop = true }
sts2-utils = { path = "sts2_utils", develop = true }


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipython (>=9.16.1,<10.0.0)",
    "pytest (>=8.0,<9.0)",
]
