[project]
name = "logit_model"
version = "0.1.0"
description = ""
authors = [
    {name = "Jim Wild",email = "james.wild@airelogic.com"}
]
requires-python = ">=3.12"
dependencies = [
    "click",
    "numpy",
    "scikit-learn",
    "sts2-utils",
]

[tool.poetry.scripts]
logit-model = "logit_model.cli:main"

[project.optional-dependencies]
test = ["pytest"]
gpu = ["cuml-cu12", "cupy-cuda12x"]

[tool.poetry]
packages = [{ include = "logit_model", from = "src" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
